language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_install:
  - curl http://apt.basho.com/gpg/basho.apt.key | sudo apt-key add -
  - sudo bash -c "echo deb http://apt.basho.com $(lsb_release -sc) main > /etc/apt/sources.list.d/basho.list"
  - sudo apt-get update -qq
  - sudo apt-get install -qq valgrind
  - sudo apt-get install -qq riak
  - sudo php ./script/configure-riak.php
  - ulimit -n 2048
before_script:
  - git submodule update --init --recursive
  - ./script/build_module.sh
  - search-cmd install testsearch
script:
  - PHP=`which php`
  - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=$PHP $PHP run-tests.php -q -m --show-diff
